# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/moses/.local/lib/python2.7/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/moses/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moses/Documents/chip8emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moses/Documents/chip8emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/moses/.local/lib/python2.7/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/moses/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moses/Documents/chip8emulator/CMakeFiles /home/moses/Documents/chip8emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moses/Documents/chip8emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chip8

# Build rule for target.
chip8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chip8
.PHONY : chip8

# fast build rule for target.
chip8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/build
.PHONY : chip8/fast

Source/Chip8.o: Source/Chip8.cpp.o
.PHONY : Source/Chip8.o

# target to build an object file
Source/Chip8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Chip8.cpp.o
.PHONY : Source/Chip8.cpp.o

Source/Chip8.i: Source/Chip8.cpp.i
.PHONY : Source/Chip8.i

# target to preprocess a source file
Source/Chip8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Chip8.cpp.i
.PHONY : Source/Chip8.cpp.i

Source/Chip8.s: Source/Chip8.cpp.s
.PHONY : Source/Chip8.s

# target to generate assembly for a file
Source/Chip8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Chip8.cpp.s
.PHONY : Source/Chip8.cpp.s

Source/Chip8instruct.o: Source/Chip8instruct.cpp.o
.PHONY : Source/Chip8instruct.o

# target to build an object file
Source/Chip8instruct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Chip8instruct.cpp.o
.PHONY : Source/Chip8instruct.cpp.o

Source/Chip8instruct.i: Source/Chip8instruct.cpp.i
.PHONY : Source/Chip8instruct.i

# target to preprocess a source file
Source/Chip8instruct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Chip8instruct.cpp.i
.PHONY : Source/Chip8instruct.cpp.i

Source/Chip8instruct.s: Source/Chip8instruct.cpp.s
.PHONY : Source/Chip8instruct.s

# target to generate assembly for a file
Source/Chip8instruct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Chip8instruct.cpp.s
.PHONY : Source/Chip8instruct.cpp.s

Source/Main.o: Source/Main.cpp.o
.PHONY : Source/Main.o

# target to build an object file
Source/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Main.cpp.o
.PHONY : Source/Main.cpp.o

Source/Main.i: Source/Main.cpp.i
.PHONY : Source/Main.i

# target to preprocess a source file
Source/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Main.cpp.i
.PHONY : Source/Main.cpp.i

Source/Main.s: Source/Main.cpp.s
.PHONY : Source/Main.s

# target to generate assembly for a file
Source/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Main.cpp.s
.PHONY : Source/Main.cpp.s

Source/Platform.o: Source/Platform.cpp.o
.PHONY : Source/Platform.o

# target to build an object file
Source/Platform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Platform.cpp.o
.PHONY : Source/Platform.cpp.o

Source/Platform.i: Source/Platform.cpp.i
.PHONY : Source/Platform.i

# target to preprocess a source file
Source/Platform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Platform.cpp.i
.PHONY : Source/Platform.cpp.i

Source/Platform.s: Source/Platform.cpp.s
.PHONY : Source/Platform.s

# target to generate assembly for a file
Source/Platform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8.dir/build.make CMakeFiles/chip8.dir/Source/Platform.cpp.s
.PHONY : Source/Platform.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chip8"
	@echo "... Source/Chip8.o"
	@echo "... Source/Chip8.i"
	@echo "... Source/Chip8.s"
	@echo "... Source/Chip8instruct.o"
	@echo "... Source/Chip8instruct.i"
	@echo "... Source/Chip8instruct.s"
	@echo "... Source/Main.o"
	@echo "... Source/Main.i"
	@echo "... Source/Main.s"
	@echo "... Source/Platform.o"
	@echo "... Source/Platform.i"
	@echo "... Source/Platform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

